In [1]:
import pandas as pd

df = pd.read_csv("pokemon_data.csv")
print (df)

       #                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49
1      2                Ivysaur    Grass  Poison  60      62       63
2      3               Venusaur    Grass  Poison  80      82       83
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123
4      4             Charmander     Fire     NaN  39      52       43
..   ...                    ...      ...     ...  ..     ...      ...
795  719                Diancie     Rock   Fairy  50     100      150
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60
799  721              Volcanion     Fire   Water  80     110      120

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
0         65       65     45           1      False
1         80       80     60           1      False
2        100      100     80           1      False
3        122      120     80           1      False
4         60       50     65           1      False
..       ...      ...    ...         ...        ...
795      100      150     50           6       True
796      160      110    110           6       True
797      150      130     70           6       True
798      170      130     80           6       True
799      130       90     70           6       True

[800 rows x 12 columns]

In [2]:
df.loc[(df['Type 1'] == 'Grass')&(df['Type 2'] == 'Poison')]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
48,43,Oddish,Grass,Poison,45,50,55,75,65,30,1,False
49,44,Gloom,Grass,Poison,60,65,70,85,75,40,1,False
50,45,Vileplume,Grass,Poison,75,80,85,110,90,50,1,False
75,69,Bellsprout,Grass,Poison,50,75,35,70,30,40,1,False
76,70,Weepinbell,Grass,Poison,65,90,50,85,45,55,1,False
77,71,Victreebel,Grass,Poison,80,105,65,100,70,70,1,False
344,315,Roselia,Grass,Poison,50,60,45,100,80,65,3,False
451,406,Budew,Grass,Poison,40,30,35,50,70,55,4,False
452,407,Roserade,Grass,Poison,60,70,65,125,105,90,4,False
651,590,Foongus,Grass,Poison,69,55,45,55,55,15,5,False
652,591,Amoonguss,Grass,Poison,114,85,70,85,80,30,5,False

In [3]:
df.loc[(df['Type 1'] == 'Grass')&(df['Type 2'] == 'Poison')&(df['Attack']<= 50)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
48,43,Oddish,Grass,Poison,45,50,55,75,65,30,1,False
451,406,Budew,Grass,Poison,40,30,35,50,70,55,4,False

In [4]:
df.loc[(df['Legendary'] == True)&(df['Type 1'] == 'Grass')]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
550,492,ShayminLand Forme,Grass,NaN,100,100,100,100,100,100,4,True
551,492,ShayminSky Forme,Grass,Flying,100,103,75,120,75,127,4,True
701,640,Virizion,Grass,Fighting,91,90,72,90,129,108,5,True

In [5]:
new_df = df.loc[(df['Type 1']=='Water')&(df['Type 2']=='Flying')&(df['HP'] >= 60)]
new_df = new_df.reset_index()
new_df

,index,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,140,130,Gyarados,Water,Flying,95,125,79,60,100,81,1,False
1,244,226,Mantine,Water,Flying,65,40,70,80,140,70,2,False
2,302,279,Pelipper,Water,Flying,60,50,100,85,70,65,3,False
3,641,580,Ducklett,Water,Flying,62,44,50,44,50,55,5,False
4,642,581,Swanna,Water,Flying,75,87,63,87,63,98,5,False

In [6]:
 df.loc[df['Name'].str.contains('Mega')]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,79,103,120,135,115,78,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,65,150,40,15,80,145,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,1,False
71,65,AlakazamMega Alakazam,Psychic,NaN,55,50,65,175,95,150,1,False
87,80,SlowbroMega Slowbro,Water,Psychic,95,75,180,130,80,30,1,False
102,94,GengarMega Gengar,Ghost,Poison,60,65,80,170,95,130,1,False
124,115,KangaskhanMega Kangaskhan,Normal,NaN,105,125,100,60,100,100,1,False
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,1,False
141,130,GyaradosMega Gyarados,Water,Dark,95,155,109,70,130,81,1,False
154,142,AerodactylMega Aerodactyl,Rock,Flying,80,135,85,70,95,150,1,False
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,106,190,100,154,100,130,1,True
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,106,150,70,194,120,140,1,True
168,154,Meganium,Grass,NaN,80,82,100,83,100,80,2,False
196,181,AmpharosMega Ampharos,Electric,Dragon,90,95,105,165,110,45,2,False
224,208,SteelixMega Steelix,Steel,Ground,75,125,230,55,95,30,2,False
229,212,ScizorMega Scizor,Bug,Steel,70,150,140,65,100,75,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False
248,229,HoundoomMega Houndoom,Dark,Fire,75,90,90,140,90,115,2,False
268,248,TyranitarMega Tyranitar,Rock,Dark,100,164,150,95,120,71,2,False
275,254,SceptileMega Sceptile,Grass,Dragon,70,110,75,145,85,145,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,80,160,80,130,80,100,3,False
283,260,SwampertMega Swampert,Water,Ground,100,150,110,95,110,70,3,False
306,282,GardevoirMega Gardevoir,Psychic,Fairy,68,85,65,165,135,100,3,False
327,302,SableyeMega Sableye,Dark,Ghost,50,85,125,85,115,20,3,False
329,303,MawileMega Mawile,Steel,Fairy,50,105,125,55,95,50,3,False
333,306,AggronMega Aggron,Steel,NaN,70,140,230,60,80,50,3,False
336,308,MedichamMega Medicham,Fighting,Psychic,60,100,85,80,85,100,3,False
339,310,ManectricMega Manectric,Electric,NaN,70,75,80,135,80,135,3,False
349,319,SharpedoMega Sharpedo,Water,Dark,70,140,70,110,65,105,3,False
354,323,CameruptMega Camerupt,Fire,Ground,70,120,100,145,105,20,3,False
366,334,AltariaMega Altaria,Dragon,Fairy,75,110,110,110,105,80,3,False
387,354,BanetteMega Banette,Ghost,NaN,64,165,75,93,83,75,3,False
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
397,362,GlalieMega Glalie,Ice,NaN,80,120,80,120,80,100,3,False
409,373,SalamenceMega Salamence,Dragon,Flying,95,145,130,120,90,120,3,False
413,376,MetagrossMega Metagross,Steel,Psychic,80,145,150,105,110,110,3,False
418,380,LatiasMega Latias,Dragon,Psychic,80,100,120,140,150,110,3,True
420,381,LatiosMega Latios,Dragon,Psychic,80,130,100,160,120,110,3,True
426,384,RayquazaMega Rayquaza,Dragon,Flying,105,180,100,180,100,115,3,True
476,428,LopunnyMega Lopunny,Normal,Fighting,65,136,94,54,96,135,4,False
494,445,GarchompMega Garchomp,Dragon,Ground,108,170,115,120,95,92,4,False
498,448,LucarioMega Lucario,Fighting,Steel,70,145,88,140,70,112,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
527,475,GalladeMega Gallade,Psychic,Fighting,68,165,95,65,115,110,4,False
591,531,AudinoMega Audino,Normal,Fairy,103,60,126,80,126,50,5,False
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True

In [7]:
df.iloc[4:11,1:6]

                         Name Type 1  Type 2  HP  Attack
4                  Charmander   Fire     NaN  39      52
5                  Charmeleon   Fire     NaN  58      64
6                   Charizard   Fire  Flying  78      84
7   CharizardMega Charizard X   Fire  Dragon  78     130
8   CharizardMega Charizard Y   Fire  Flying  78     104
9                    Squirtle  Water     NaN  44      48
10                  Wartortle  Water     NaN  59      63

In [8]:
df.loc[(df['Name']=='Charmander')&(df['HP'] == 39)&(df['Attack']==52)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [9]:
df.loc[df['Type 1'] == 'Grass', 'Type 1'] ='Rumput'
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Rumput,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Rumput,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Rumput,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Rumput,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [10]:
df.loc[df['Attack'] >100,['Generation','Legendary']] ='Too OP'
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Rumput,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Rumput,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Rumput,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Rumput,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,Too OP,Too OP
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,Too OP,Too OP
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,Too OP,Too OP
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,Too OP,Too OP

In [11]:
df = pd.read_csv('pokemon_data.csv')
df.loc[df['Attack']> 100,['Generation','Legendary']] = ['Gen OP', 'LegenOP']
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,Gen OP,LegenOP
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,Gen OP,LegenOP
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,Gen OP,LegenOP
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,Gen OP,LegenOP

In [12]:
df.groupby(["Type 1"]).mean(numeric_only=True)

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
Type 1,,,,,,,
Bug,334.492754,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159
Dark,461.354839,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290
Dragon,474.375000,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250
Electric,363.500000,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000
Fairy,449.529412,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235
Fighting,363.851852,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074
Fire,327.403846,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308
Flying,677.750000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000
Ghost,486.500000,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750
Grass,344.871429,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571
Ground,356.281250,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250
Ice,423.541667,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333
Normal,319.173469,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020
Poison,251.785714,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429
Psychic,380.807018,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228
Rock,392.727273,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091
Steel,442.851852,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259
Water,303.089286,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286